apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system-service
  annotations:
    service.oks.outscale.com/source-ranges: "0.0.0.0/0"

spec:
  ports:
  - port: 80 #change to 80
    protocol: TCP
    targetPort: 80 #change to 80
    nodePort: 33333
  selector:
    app: solar-system
  type: NodePort
